package analizador_lexico;

public enum Estado {
    INICIO,
    PALABRA_RESERVADA,
    IDENTIFICADOR,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    OPERADOR_ARITMETICO,
    INCREMENTO,
    DECREMENTO,
    ASIGNACION,
    NUMERO_ENTERO,
    NUMERO_DECIMAL,
    CADENA_CARACTERES,
    COMENTARIO,
    COMENTARIO_LINEA,
    PARENTESIS,
    LLAVE,
    DESCONOCIDO
}
